### ISSUE TITLE
Very laggy?

### ISSUE THREAD

**Issue by zakkor** [indrajithi/Audio-Visualizer#3]
The program runs at about 3 FPS, is the issue on my end?

**Comment by indrajithi** [comment]
No. This issue is with the OpenGL, which I know very little to fix. If the sample rate is 44.1 kHz, the solution is to choose N as 2048 to get a frequency resolution of 21.5 Hz  and 25fps. But when we choose N as 2048 there is 3x difference in sync with the audio. You can change glutIdleFunc() for better synchronization. There is `draw2.cpp` in branch `develop` where the frequency calculation is done before the OpenGL function calls. The result is the same.
